### ISSUE TITLE
cmake "make install" does not install icon and .desktop file

### ISSUE THREAD

**Issue by csete** [gqrx-sdr/gqrx#311] opened 2015-12-09 21:17 UTC

**Comment by xand79** [comment] 2015-12-16 11:53
Well, I have install it too with the same problem on Xubuntu 14.04 LTS. After deinstall previous version. Via 'apt-get install gqrx-sdr'. And I can't see icons at buttons on the bar (but buttons are working). Where to add it if I can?
Thanks for your great job :)

**Comment by csete** [comment] 2015-12-16 18:47
> And I can't see icons at buttons on the bar (but buttons are working)

That sounds like a different issue. I think you need to install QtSvg module. Are you sure you use version 2.4 from the new PPA?

**Comment by xand79** [comment] 2015-12-17 17:36
Help > About Gqrx: "This is Gqrx 2.4". Yes. It's from PPA. And I have libqt4-svg 4:4.8.5+git192-g085f851+dfsg-2ubuntu4.1 installed... Maybe I need other version?

**Comment by csete** [comment] 2015-12-17 19:09
Actually, yes. Gqrx in the PPA has been linked against Qt 5 so you will need the libqt5svg package. I will try fixing the package so that Qt SVG also becomes a runtime dependency (I thought it was already done)

**Comment by xand79** [comment] 2015-12-17 19:51
Big thanks for a hint! I have installed "libqt5svg5 5.2.1-1" and now can see all icons!

**Comment by pinkavaj** [comment] 2022-11-07 10:29
I cannot reproduce this error any more. @csete Can you or anyone else?

If no reponse or cannot be reproduced I'm suggesting to close this at 2022 year end.

**Comment by vladisslav2011** [comment] 2022-11-07 10:58
It is already fixed: https://github.com/gqrx-sdr/gqrx/blob/master/CMakeLists.txt#L270-L277

**Comment by pinkavaj** [comment] 2022-11-07 13:36
@argilo Seem like we can close this one, but I likely does not have the permissions. I can try to do more clean-up in the tickets, if it is not considered contraproductive, what is the suggested workflow, should I tag you in the others ticket considered to close too?

**Comment by argilo** [comment] 2022-11-07 14:12
Fixed in #1074.

**Comment by argilo** [comment] 2022-11-07 14:13
> should I tag you in the others ticket considered to close too?

Yes, if there are other tickets that should be closed, just tag me and I'll close them. Thanks for your help!

**Closed by argilo** 2022-11-07 14:12 UTC
Labels: bug
