### ISSUE TITLE
Apple Silicon / M1 builds?

### ISSUE THREAD

**Issue by drwetter** [gqrx-sdr/gqrx#1104] opened 2022-02-09 21:55 UTC
Are there any plans to supply builds for the new architecture? Even hombrew fails (_Bad CPU type in executable_).

Are there any obstacles since qt6 works on aarch64?

**Comment by argilo** [comment] 2022-02-09 23:03
I would like the macOS builds to have M1 support. I just don't have the expertise (or hardware) to work on this at the moment.

One obstacle is that the Gqrx build currently uses gnuradio from Homebrew, which does not support M1:

https://github.com/gqrx-sdr/gqrx/blob/f108a292e400ada937cad27e80748eca23da448f/.github/workflows/build.yml#L89

https://formulae.brew.sh/formula/gnuradio

One possibility would be to build Gqrx's dependencies from source, instead of installing them from Homebrew. This would slow down builds, but perhaps they could be sped up again using ccache.

If anyone has expertise in building software with M1 support, I'd appreciate help.

**Comment by drwetter** [comment] 2022-02-10 07:46
FYI (but probably doesn't help much): I tried yesterday to compile gnuradio via homebrew. It stopped when compiling volk as dependency (error when compiling volk_machine_neonv8.c. It did only state the clang command but not the actual error).

**Comment by vielmetti** [comment] 2022-04-04 01:31
The "volk doesn't build on M1" issue is https://github.com/gnuradio/volk/issues/428 upstream, which is said to be fixed by https://github.com/google/cpu_features/commit/69d39934e83be9a0133d2850f15f5debd5eba06f reported in https://github.com/google/cpu_features/issues/179 with a PR in https://github.com/google/cpu_features/pull/209 - which as much to say that it might be worth revisiting this issue if indeed the problems are resolved.

**Comment by vielmetti** [comment] 2022-04-04 01:51
I was just now able to install "volk" with Home-brew, getting this:

==> Pouring volk--2.5.1_1.arm64_monterey.bottle.tar.gz

and no errors.

**Comment by vielmetti** [comment] 2022-04-04 03:24
Yup, and GNU Radio now installs OK

==> Pouring gnuradio--3.9.3.0_4.arm64_monterey.bottle.tar.gz

**Comment by dsegel** [comment] 2022-04-16 03:30
I just installed v2.15.9 (I don't understand the version numbering) via homebrew (brew install gqrx) and it runs fine on my M1 MacBook Air.

`==> Downloading https://github.com/gqrx-sdr/gqrx/releases/download/v2.15.9/Gqrx-2.15.9.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/1033271/0074ad10-fcdb-4e9d-abac-c837c0
######################################################################## 100.0%
==> Installing Cask gqrx
==> Moving App 'Gqrx.app' to '/Applications/Gqrx.app'
==> Linking Binary 'gqrx.wrapper.sh' to '/opt/homebrew/bin/gqrx'
🍺  gqrx was successfully installed!
`

**Comment by Forst** [comment] 2022-07-18 23:23
I gave a quick and dirty go at building Gqrx for M1. Looking at `.github/workflow/build.yml`, the only major difference is Homebrew is installed in `/opt/homebrew` on Apple Silicon platforms instead of `/usr/local` on Intel. This affects all mentions of `/usr/local` in the build scripts, and needs to be defined as the cmake install prefix for certain dependencies.

Built and tested on macOS 12.4. Tested with RTL-SDR (USB), seems to work alright:

<img width="1009" alt="Screenshot 2022-07-19 at 01 19 02" src="https://user-images.githubusercontent.com/369699/179632725-3a76cf83-8e16-4e1a-8f30-d6ce61324b5b.png">

<img width="1728" alt="Screenshot 2022-07-19 at 01 21 23" src="https://user-images.githubusercontent.com/369699/179632938-f4f6fec5-7cac-440a-bff5-3c31b3eb0c73.png">

I put together a build script from `.github/workflow/build.yml` and `macos_bundle.sh`, posted here: https://gist.github.com/Forst/db68106136be3380086e3c38be094d99

Note that I am a total noob when it comes to building apps for macOS, so I just changed things around until it worked :)

**Comment by danielktdoranie** [comment] 2023-03-03 21:02
> I gave a quick and dirty go at building Gqrx for M1. Looking at `.github/workflow/build.yml`, the only major difference is Homebrew is installed in `/opt/homebrew` on Apple Silicon platforms instead of `/usr/local` on Intel. This affects all mentions of `/usr/local` in the build scripts, and needs to be defined as the cmake install prefix for certain dependencies.
> 
> Built and tested on macOS 12.4. Tested with RTL-SDR (USB), seems to work alright:
> 
> <img alt="Screenshot 2022-07-19 at 01 19 02" width="1009" src="https://user-images.githubusercontent.com/369699/179632725-3a76cf83-8e16-4e1a-8f30-d6ce61324b5b.png">
> 
> <img alt="Screenshot 2022-07-19 at 01 21 23" width="1728" src="https://user-images.githubusercontent.com/369699/179632938-f4f6fec5-7cac-440a-bff5-3c31b3eb0c73.png">
> 
> I put together a build script from `.github/workflow/build.yml` and `macos_bundle.sh`, posted here: https://gist.github.com/Forst/db68106136be3380086e3c38be094d99
> 
> Note that I am a total noob when it comes to building apps for macOS, so I just changed things around until it worked :)

Hey sir any hope of you dropping that .dmg file somewhere so I can try it?

**Comment by Forst** [comment] 2023-03-10 21:45
> Hey @Forst any hope of you dropping that .dmg file somewhere so I can try it?

@danielktdoranie Here you go: https://drive.proton.me/urls/N8C7JTHZB0#HJbeqbOBA2HA. It's the same dmg from July last year, luckily I had it lying around.

Be wary of running programs from strangers on the internet. I posted the build script in my earlier comment so you could reproduce the results yourself with code you can audit/verify.

**Comment by danielktdoranie** [comment] 2023-03-11 11:10
> > Hey @Forst any hope of you dropping that .dmg file somewhere so I can try it?
> 
> @danielktdoranie Here you go: https://drive.proton.me/urls/N8C7JTHZB0#HJbeqbOBA2HA. It's the same dmg from July last year, luckily I had it lying around.
> 
> Be wary of running programs from strangers on the internet. I posted the build script in my earlier comment so you could reproduce the results yourself with code you can audit/verify.

Thanks. Yeah, I need to learn to compile programs myself but I really wish the developer would put this version up on the main webpage for SDR normies like myself. Thanks for providing this!

**Comment by argilo** [comment] 2024-04-05 14:51
I see conda-forge has an osx-arm64 build: https://anaconda.org/conda-forge/gqrx

Gqrx Linux builds were recently switched over to conda (#1301), so perhaps conda could be a replacement for homebrew on macOS as well.

**Comment by kgarrels** [comment] 2024-04-05 15:23
I am building gqrx with radioconda on macOS 12, works without problem.
I am still using Intel, and I am using local builds, not github actions.

**Comment by kgarrels** [comment] 2024-10-18 17:12
in the meantime, I switched to ARM, gqrx build and works fine with radioconda.
I use Qt5, Qt6 is not yet avaiable for mac on radioconda.

Can I help somhow? I am not experienced with github actions, but I can record all steps from a clean macos 14 install until build. Would that help?

**Comment by yuzawa-san** [comment] 2024-10-21 22:36
i gave my attempt at this in https://github.com/gqrx-sdr/gqrx/pull/1388 please try out the build artifacts. looks like they are still not signed in the PR build probably for security reasons. maybe the maintainers need to trigger a rerun so the secrets will populate. my friend had trouble opening the unsigned app in their arm64 sequoia environment.

**Closed** 2024-11-09 17:51 UTC
Labels: feature
