### ISSUE TITLE
C-QUAM mode support

### ISSUE THREAD

**Issue by AsciiWolf** [gqrx-sdr/gqrx#1159] opened 2022-11-03 23:22 UTC
It would be great if Gqrx had [C-QUAM](https://en.wikipedia.org/wiki/C-QUAM) demodulator. C-QUAM (Compatible QUadrature Amplitude Modulation) is a method of AM stereo broadcasting used in many countries. It offers stereo sound and much better audio quality than regular AM.

**Comment by argilo** [comment] 2022-11-03 23:27
This is a duplicate of #938, so I'll close it off.

**Closed by argilo** 2022-11-03 23:27 UTC

**Comment by AsciiWolf** [comment] 2022-11-03 23:30
Oops! I did search "C-QUAM" before creating this ticket and found no existing tickets + I completely forgot about the existing ticket (even though I made a comment in it *sigh*). Sorry for creating a duplicate.
