### ISSUE TITLE
Frequency Correction Pulsing

### ISSUE THREAD

**Issue by znorris** [gqrx-sdr/gqrx#69] opened 2013-06-01 16:43 UTC
When using a E4000 with a sample rate of 3200000Hz changing the "Frequency corr." field results in a pulsing across the entire sample range. It can be seen on the spectrum analyzer and heard in the audio.
Returning frequency corr. to 0 may or may not fix the problem. Turning the sample rate down  does seem to correct the problem.

**Comment by xand79** [comment] 2015-12-16 11:31
Maybe I found something similar to this problem. I use Xubuntu 14.04 LTS and RTL DVB with R820T. My freq. correction is about 38 ppm. With new version of Gqrx I found that when I'm reloading program, correction is still right, but signal is again lower then must be. Okay, I'm setting correction to 0 ppm, reloading Gqrx and again setting it to 38 ppm -> all great. Then quit, load again -> signal is lower again, while program still remember 38.
Maybe it will help you to find bug :)

**Comment by pinkavaj** [comment] 2022-11-07 10:13
Is this till reproducible? By my opinion this is likely relevant to rtlsdr it-self. Also this pushes the device to it's limits.

If there will be no progress til end of the year 2022, I'm suggesting to close this (I will do that if nobody steps-in).

**Comment by vladisslav2011** [comment] 2022-11-07 10:54
I can't reproduce this using my devices.

**Comment by argilo** [comment] 2022-11-07 19:42
I still hear crackling in the audio when I push the RTL-SDR sample rate up to 2.88 or 3.2 Msps. As far as I know, this is a known hardware limitation in the RTL-SDR and not a bug in Gqrx, so I'll close this off.

**Closed by argilo** 2022-11-07 19:42 UTC
Labels: bug
