### ISSUE TITLE
Failed to open rtlsdr device

### ISSUE THREAD

**Issue by dltkddnr04** [gqrx-sdr/gqrx#1114] opened 2022-03-21 13:06 UTC
Hello.
When I finish setting up the device and click the OK button, the following warning window appears.
And I can't use SDR through the program.

<img width="441" alt="스크린샷 2022-03-21 오후 9 55 27" src="https://user-images.githubusercontent.com/37734227/159266512-61e6101d-ea21-448d-80d6-e8b5ab2e1bd9.png">
<img width="432" alt="스크린샷 2022-03-21 오후 9 55 06" src="https://user-images.githubusercontent.com/37734227/159266527-583de076-3da3-426b-a226-d1fc69544d5d.png">

Does anyone know a solution to this problem?
I think it could be a problem with macos beta.
thanks.

Here are the specs I use
- Macbook Pro 13' 2015
- macOS 12.3 (21E230)
- GQRX 2.15.8
- RTL_SDR dongle(rtl2838u chip, blue one)

**Comment by vladisslav2011** [comment] 2022-03-22 21:09
Hello.
Try running gqrx with sudo.
If it helps, then read here: https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_vm_device-access

**Comment by dltkddnr04** [comment] 2022-03-26 08:01
I tried with sudo and this is the same as before.
I can't understand what happened.

**Comment by vladisslav2011** [comment] 2022-03-26 08:27
Could you check your dongle with rtl_fm (it may require sudo due to macos hardware access restrictions)? If it does not work too, try connecting the dongle to another USB port or connecting it through a hub/docking station.

**Comment by dltkddnr04** [comment] 2022-03-27 14:21
I tried the rtl_fm command and the result is below

$ sudo rtl_fm -f 105900000         
Found 1 device(s):
  0:  , , SN: 
Using device 0: Generic RTL2832U OEM
rtlsdr_write_reg failed with -1
Resetting device...
zsh: segmentation fault  sudo rtl_fm -f 105900000

Is it possible that the SDR device failure is the cause?

**Comment by vladisslav2011** [comment] 2022-03-27 18:42
It's unlikely, that the SDR device failure is the cause.
The error code -1 means "Operation not permitted",  so there is some configuration problem. libusb can't access the device.
That's not gqrx issue as the rtl_fm have problems accessing a device too.

**Comment by argilo** [comment] 2023-04-28 20:53
It appears this issue is not due to a problem in Gqrx, so I'll close it off.

**Closed by argilo** 2023-04-28 20:53 UTC
Labels: bug
